import type { editor } from 'monaco-editor';

/**
 * Aura Dark for Monaco.
 * Colors adapted from https://github.com/daltonmenezes/aura-theme (MIT).
 */
export const AURA_DARK_THEME: editor.IStandaloneThemeData = {
    base: 'vs-dark',
    inherit: true,
    rules: [
        { token: '', foreground: 'edecee' },
        { token: 'comment', foreground: '6d6d6d', fontStyle: 'italic' },
        { token: 'string', foreground: '61ffca' },
        { token: 'string.escape', foreground: '61ffca' },
        { token: 'keyword', foreground: 'a277ff' },
        { token: 'keyword.control', foreground: 'a277ff' },
        { token: 'keyword.operator', foreground: 'a277ff' },
        { token: 'storage', foreground: 'a277ff' },
        { token: 'storage.type', foreground: 'a277ff' },
        { token: 'number', foreground: '61ffca' },
        { token: 'regexp', foreground: '61ffca' },
        { token: 'constant', foreground: '61ffca' },
        { token: 'constant.language', foreground: '61ffca' },
        { token: 'constant.numeric', foreground: '61ffca' },
        { token: 'type', foreground: '82e2ff' },
        { token: 'type.identifier', foreground: '82e2ff' },
        { token: 'class', foreground: '82e2ff' },
        { token: 'class.name', foreground: '82e2ff' },
        { token: 'tag', foreground: 'a277ff' },
        { token: 'tag.id', foreground: '61ffca' },
        { token: 'tag.class', foreground: 'a277ff' },
        { token: 'attribute.name', foreground: 'f694ff' },
        { token: 'attribute.value', foreground: '61ffca' },
        { token: 'meta.tag', foreground: 'a277ff' },
        { token: 'metatag', foreground: 'a277ff' },
        { token: 'metatag.content', foreground: '61ffca' },
        { token: 'key', foreground: 'f694ff' },
        { token: 'key.identifier', foreground: 'f694ff' },
        { token: 'variable', foreground: 'edecee' },
        { token: 'variable.name', foreground: 'edecee' },
        { token: 'variable.predefined', foreground: 'a277ff' },
        { token: 'identifier', foreground: 'edecee' },
        { token: 'delimiter', foreground: 'edecee' },
        { token: 'delimiter.html', foreground: 'edecee' },
        { token: 'delimiter.xml', foreground: 'edecee' },
        { token: 'operator', foreground: 'a277ff' },
        { token: 'annotation', foreground: 'ffca85' },
        { token: 'invalid', foreground: 'ff6767' },
    ],
    colors: {
        'editor.background': '#15141b',
        'editor.foreground': '#edecee',
        'editorLineNumber.foreground': '#a394f033',
        'editorLineNumber.activeForeground': '#a394f0',
        'editorCursor.foreground': '#a277ff',
        'editor.selectionBackground': '#3d375e7f',
        'editor.inactiveSelectionBackground': '#3d375e7f',
        'editor.selectionHighlightBackground': '#3d375e7f',
        'editor.wordHighlightBackground': '#3d375e7f',
        'editor.wordHighlightStrongBackground': '#3d375e7f',
        'editor.findMatchBackground': '#3d375e7f',
        'editor.findMatchHighlightBackground': '#3d375e7f',
        'editor.lineHighlightBackground': '#a394f033',
        'editor.lineHighlightBorder': '#a394f000',
        'editorWhitespace.foreground': '#2d2d2d',
        'editorIndentGuide.background': '#2d2d2d',
        'editorIndentGuide.activeBackground': '#6d6d6d',
        'editorBracketMatch.border': '#a277ff',
        'editorError.foreground': '#ff6767',
        'editorWarning.foreground': '#ffca85',
        'editorGutter.background': '#15141b',
        'editorGutter.modifiedBackground': '#ffca85',
        'editorGutter.addedBackground': '#61ffca',
        'editorGutter.deletedBackground': '#ff6767',
        'editorWidget.background': '#121016',
        'editorWidget.border': '#2d2d2d',
        'editorHoverWidget.background': '#121016',
        'editorHoverWidget.border': '#2d2d2d',
        'scrollbar.shadow': '#00000000',
        'scrollbarSlider.background': '#79797966',
        'scrollbarSlider.hoverBackground': '#646464b3',
        'scrollbarSlider.activeBackground': '#bfbfbf66',
        // Diff highlights from Aura; overview ruler kept strong for review readability.
        'diffEditor.insertedTextBackground': '#00d89023',
        'diffEditor.removedTextBackground': '#ff474720',
        'diffEditor.insertedLineBackground': '#00d89014',
        'diffEditor.removedLineBackground': '#ff474714',
        'diffEditorOverview.insertedForeground': '#61ffca',
        'diffEditorOverview.removedForeground': '#ff6767',
    },
};
