export const styles = {
    root: 'flex min-h-0 flex-1 flex-col bg-zinc-950 pb-[env(safe-area-inset-bottom)] md:flex-row',
    editorPanel: 'flex min-h-0 flex-1 flex-col md:min-w-0',
    editorPanelMobileHidden: 'hidden min-h-0 flex-1 flex-col md:flex md:min-w-0',
    listPanelWrap:
        'relative flex min-h-0 flex-1 flex-col overflow-visible md:h-full md:flex-none md:shrink-0 md:border-r md:border-zinc-800',
    listPanelWrapMobileHidden:
        'hidden min-h-0 md:relative md:flex md:h-full md:flex-none md:shrink-0 md:overflow-visible md:border-r md:border-zinc-800',
    listPanel: 'flex h-full min-h-0 w-full flex-1 flex-col',
    listPanelMobileHidden: 'hidden h-full min-h-0 w-full flex-col md:flex',
    fileTreeResize: 'z-30',
    toolbar: 'flex h-7 shrink-0 items-center border-b border-zinc-800 bg-zinc-900 px-3',
    toolbarTitle: 'min-w-0 truncate text-xs text-zinc-400',
    centered: 'flex flex-1 items-center justify-center px-4 text-sm text-zinc-500',
    fileList: 'code-review-scroll min-h-0 flex-1 overflow-y-auto',
    treeRow:
        'flex w-full items-center gap-2 border-b border-zinc-900/80 py-2 pr-3 text-left active:bg-zinc-900/80 md:hover:bg-zinc-900/80',
    treeRowSelected: 'bg-zinc-900/80',
    dirButton: 'text-zinc-300',
    fileButton: 'text-zinc-100',
    chevron: 'h-3.5 w-3.5 shrink-0 text-zinc-500 transition-transform',
    chevronCollapsed: 'h-3.5 w-3.5 shrink-0 -rotate-90 text-zinc-500 transition-transform',
    chevronSpacer: 'h-3.5 w-3.5 shrink-0',
    folderIcon: 'h-4 w-4 shrink-0 text-zinc-500',
    statusBadge: 'inline-flex h-5 w-5 shrink-0 items-center justify-center rounded text-[10px] font-semibold',
    statusAdded: 'bg-emerald-500/15 text-emerald-400',
    statusModified: 'bg-amber-400/15 text-amber-300',
    statusDeleted: 'bg-red-500/15 text-red-400',
    statusRenamed: 'bg-sky-500/15 text-sky-300',
    fileMeta: 'min-w-0 flex-1',
    nodeLabel: 'min-w-0 flex-1 truncate font-mono text-[12px]',
    dirLabel: 'text-zinc-300',
    fileLabel: 'block truncate font-mono text-[12px] text-zinc-100',
    renameHint: 'block truncate font-mono text-[10px] text-zinc-500',
    fileStats: 'ml-auto shrink-0 font-mono text-[10px]',
    additions: 'text-emerald-400',
    deletions: 'text-red-400',
    fileHeader: 'flex h-7 shrink-0 items-center gap-2 border-b border-zinc-800 bg-zinc-900 px-2 md:px-4',
    backButton:
        'inline-flex h-6 w-6 shrink-0 items-center justify-center rounded-md text-zinc-100 active:bg-zinc-800 md:hidden',
    backIcon: 'h-4 w-4 shrink-0',
    fileHeaderPath: 'min-w-0 flex-1 truncate font-mono text-xs text-zinc-200',
    fileHeaderMode:
        'inline-flex h-6 w-6 shrink-0 items-center justify-center rounded-md text-zinc-400 transition-colors active:bg-zinc-800 active:text-zinc-100 md:hover:bg-zinc-800/80 md:hover:text-zinc-100',
    fileHeaderModeIcon: 'h-4 w-4',
    markdownViewPane: 'flex min-h-0 flex-1 flex-col',
    markdownViewHidden: 'hidden',
    editorWrap: 'relative min-h-0 flex-1',
    editorFill: 'absolute inset-0',
    markdownPreview: 'code-review-scroll min-h-0 flex-1 overflow-y-auto',
    markdownBody: 'mx-auto max-w-3xl px-4 py-6 text-sm leading-relaxed text-zinc-200 md:px-8',
    mdH1: 'mb-4 border-b border-zinc-800 pb-2 text-2xl font-semibold tracking-tight text-zinc-50',
    mdH2: 'mb-3 mt-8 border-b border-zinc-800/80 pb-1.5 text-xl font-semibold tracking-tight text-zinc-50',
    mdH3: 'mb-2 mt-6 text-lg font-semibold text-zinc-100',
    mdH4: 'mb-2 mt-5 text-base font-semibold text-zinc-100',
    mdP: 'mb-4 text-zinc-300',
    mdLink: 'text-aura-blue underline decoration-aura-blue/40 underline-offset-2 hover:text-sky-300',
    mdUl: 'mb-4 list-disc space-y-1 pl-5 text-zinc-300',
    mdOl: 'mb-4 list-decimal space-y-1 pl-5 text-zinc-300',
    mdLi: 'leading-relaxed',
    mdBlockquote: 'mb-4 border-l-2 border-zinc-600 pl-4 text-zinc-400 italic',
    mdHr: 'my-8 border-zinc-800',
    mdTableWrap: 'mb-4 overflow-x-auto',
    mdTable: 'w-full border-collapse text-left text-sm',
    mdThead: 'border-b border-zinc-700',
    mdTh: 'px-3 py-2 font-semibold text-zinc-200',
    mdTd: 'border-t border-zinc-800/80 px-3 py-2 text-zinc-300',
    mdInlineCode: 'rounded bg-zinc-800 px-1.5 py-0.5 font-mono text-[0.85em] text-zinc-100',
    mdPre: 'mb-4 overflow-x-auto rounded-lg border border-zinc-800 bg-zinc-900 p-3 font-mono text-[12px] leading-5 text-zinc-100',
    mdImg: 'my-4 max-w-full rounded-md',
};
