export const styles = {
    root: 'flex min-h-0 flex-1 flex-col bg-zinc-950 pb-[env(safe-area-inset-bottom)] md:flex-row',
    editorPanel: 'flex min-h-0 flex-1 flex-col md:min-w-0',
    editorPanelMobileHidden: 'hidden min-h-0 flex-1 flex-col md:flex md:min-w-0',
    listPanelWrap: 'relative flex min-h-0 flex-1 flex-col overflow-visible md:h-full md:flex-none md:shrink-0',
    listPanelWrapMobileHidden:
        'hidden min-h-0 md:relative md:flex md:h-full md:flex-none md:shrink-0 md:overflow-visible',
    listPanel: 'flex h-full min-h-0 w-full flex-1 flex-col md:border-r md:border-zinc-800',
    listPanelMobileHidden: 'hidden h-full min-h-0 w-full flex-col md:flex',
    fileTreeResize: 'z-30',
    toolbar: 'flex items-center justify-between gap-2 border-b border-zinc-800 px-3 py-2',
    toolbarTitle: 'min-w-0 truncate text-xs text-zinc-400',
    toolbarActions: 'flex shrink-0 items-center gap-2',
    refreshButton: 'shrink-0 text-xs font-medium text-zinc-300',
    centered: 'flex flex-1 items-center justify-center px-4 text-sm text-zinc-500',
    fileList: 'min-h-0 flex-1 overflow-y-auto',
    treeRow:
        'flex w-full items-center gap-2 border-b border-zinc-900/80 py-2 pr-3 text-left active:bg-zinc-900/80 md:hover:bg-zinc-900/80',
    treeRowSelected: 'bg-zinc-900/80',
    dirButton: 'text-zinc-300',
    fileButton: 'text-zinc-100',
    chevron: 'h-3.5 w-3.5 shrink-0 text-zinc-500 transition-transform',
    chevronCollapsed: 'h-3.5 w-3.5 shrink-0 -rotate-90 text-zinc-500 transition-transform',
    chevronSpacer: 'h-3.5 w-3.5 shrink-0',
    folderIcon: 'h-4 w-4 shrink-0 text-zinc-500',
    statusBadge: 'inline-flex h-5 w-5 shrink-0 items-center justify-center rounded text-[10px] font-semibold',
    statusAdded: 'bg-emerald-500/15 text-emerald-400',
    statusModified: 'bg-amber-400/15 text-amber-300',
    statusDeleted: 'bg-red-500/15 text-red-400',
    statusRenamed: 'bg-sky-500/15 text-sky-300',
    fileMeta: 'min-w-0 flex-1',
    nodeLabel: 'min-w-0 flex-1 truncate font-mono text-[12px]',
    dirLabel: 'text-zinc-300',
    fileLabel: 'block truncate font-mono text-[12px] text-zinc-100',
    renameHint: 'block truncate font-mono text-[10px] text-zinc-500',
    fileStats: 'hidden shrink-0 font-mono text-[10px] lg:inline',
    additions: 'text-emerald-400',
    deletions: 'text-red-400',
    fileHeader: 'flex shrink-0 items-center gap-2 border-b border-zinc-800 px-2 py-1.5 md:px-4',
    backButton:
        'inline-flex min-h-11 shrink-0 items-center gap-1.5 rounded-md bg-zinc-900 px-3 py-2 text-sm font-medium text-zinc-100 active:bg-zinc-800 md:hidden',
    backIcon: 'h-5 w-5 shrink-0',
    fileHeaderPath: 'min-w-0 flex-1 truncate font-mono text-xs text-zinc-200',
    editorWrap: 'relative min-h-0 flex-1',
    editorFill: 'absolute inset-0',
};
