export const styles = {
    root: 'fixed inset-0 z-20 flex flex-col bg-zinc-950 text-zinc-100',
    header: 'flex items-center justify-between px-4 pt-[max(0.75rem,env(safe-area-inset-top))] pb-3',
    title: 'text-xl font-semibold tracking-tight',
    content: 'flex min-h-0 flex-1 flex-col gap-2 overflow-auto px-4',
    empty: 'mt-8 text-center text-sm text-zinc-500',
    link: 'text-zinc-300 underline underline-offset-2',
    error: 'text-sm text-red-400',
    confirmError: 'mt-4 text-sm text-red-400',
    loading: 'mt-8 text-center text-sm text-zinc-500',
    option: 'w-full rounded-lg border border-zinc-800 bg-zinc-900 px-4 py-4 text-left text-base font-medium text-zinc-100 transition-colors active:bg-zinc-800',
    optionSelected: 'border-zinc-100 bg-zinc-800',
    footer: 'flex flex-col gap-3 border-t border-zinc-900 px-4 pt-4 pb-[max(1.5rem,env(safe-area-inset-bottom))]',
    footerRow: 'flex gap-3',
    footerButton: 'flex-1',
    confirmBody: 'flex flex-1 flex-col items-center justify-center px-6 text-center',
    confirmQuestion: 'text-lg font-medium text-zinc-100',
    confirmPath: 'mt-3 text-sm text-zinc-500',
};
