import type { editor } from 'monaco-editor';
import { AURA } from '@ui/libs/theme/aura';

/**
 * Aura Dark for Monaco.
 * Colors adapted from https://github.com/daltonmenezes/aura-theme (MIT).
 */
export const AURA_DARK_THEME: editor.IStandaloneThemeData = {
    base: 'vs-dark',
    inherit: true,
    rules: [
        { token: '', foreground: stripHash(AURA.foreground) },
        { token: 'comment', foreground: stripHash(AURA.comment), fontStyle: 'italic' },
        { token: 'string', foreground: stripHash(AURA.green) },
        { token: 'string.escape', foreground: stripHash(AURA.green) },
        { token: 'keyword', foreground: stripHash(AURA.purple) },
        { token: 'keyword.control', foreground: stripHash(AURA.purple) },
        { token: 'keyword.operator', foreground: stripHash(AURA.purple) },
        { token: 'storage', foreground: stripHash(AURA.purple) },
        { token: 'storage.type', foreground: stripHash(AURA.purple) },
        { token: 'number', foreground: stripHash(AURA.green) },
        { token: 'regexp', foreground: stripHash(AURA.green) },
        { token: 'constant', foreground: stripHash(AURA.green) },
        { token: 'constant.language', foreground: stripHash(AURA.green) },
        { token: 'constant.numeric', foreground: stripHash(AURA.green) },
        { token: 'type', foreground: stripHash(AURA.blue) },
        { token: 'type.identifier', foreground: stripHash(AURA.blue) },
        { token: 'class', foreground: stripHash(AURA.blue) },
        { token: 'class.name', foreground: stripHash(AURA.blue) },
        { token: 'tag', foreground: stripHash(AURA.purple) },
        { token: 'tag.id', foreground: stripHash(AURA.green) },
        { token: 'tag.class', foreground: stripHash(AURA.purple) },
        { token: 'attribute.name', foreground: stripHash(AURA.pink) },
        { token: 'attribute.value', foreground: stripHash(AURA.green) },
        { token: 'meta.tag', foreground: stripHash(AURA.purple) },
        { token: 'metatag', foreground: stripHash(AURA.purple) },
        { token: 'metatag.content', foreground: stripHash(AURA.green) },
        { token: 'key', foreground: stripHash(AURA.pink) },
        { token: 'key.identifier', foreground: stripHash(AURA.pink) },
        { token: 'variable', foreground: stripHash(AURA.foreground) },
        { token: 'variable.name', foreground: stripHash(AURA.foreground) },
        { token: 'variable.predefined', foreground: stripHash(AURA.purple) },
        { token: 'identifier', foreground: stripHash(AURA.foreground) },
        { token: 'delimiter', foreground: stripHash(AURA.foreground) },
        { token: 'delimiter.html', foreground: stripHash(AURA.foreground) },
        { token: 'delimiter.xml', foreground: stripHash(AURA.foreground) },
        { token: 'operator', foreground: stripHash(AURA.purple) },
        { token: 'annotation', foreground: stripHash(AURA.orange) },
        { token: 'invalid', foreground: stripHash(AURA.red) },
    ],
    colors: {
        'editor.background': AURA.background,
        'editor.foreground': AURA.foreground,
        'editorLineNumber.foreground': AURA.purpleMutedSoft,
        'editorLineNumber.activeForeground': AURA.purpleMuted,
        'editorCursor.foreground': AURA.purple,
        'editor.selectionBackground': AURA.selection,
        'editor.inactiveSelectionBackground': AURA.selection,
        'editor.selectionHighlightBackground': AURA.selection,
        'editor.wordHighlightBackground': AURA.selection,
        'editor.wordHighlightStrongBackground': AURA.selection,
        'editor.findMatchBackground': AURA.selection,
        'editor.findMatchHighlightBackground': AURA.selection,
        'editor.lineHighlightBackground': AURA.purpleMutedSoft,
        'editor.lineHighlightBorder': '#a394f000',
        'editorWhitespace.foreground': AURA.border,
        'editorIndentGuide.background': AURA.border,
        'editorIndentGuide.activeBackground': AURA.comment,
        'editorBracketMatch.border': AURA.purple,
        'editorError.foreground': AURA.red,
        'editorWarning.foreground': AURA.orange,
        'editorGutter.background': AURA.background,
        'editorGutter.modifiedBackground': AURA.orange,
        'editorGutter.addedBackground': AURA.green,
        'editorGutter.deletedBackground': AURA.red,
        'editorWidget.background': AURA.backgroundWidget,
        'editorWidget.border': AURA.border,
        'editorHoverWidget.background': AURA.backgroundWidget,
        'editorHoverWidget.border': AURA.border,
        'scrollbar.shadow': '#00000000',
        'scrollbarSlider.background': '#79797966',
        'scrollbarSlider.hoverBackground': '#646464b3',
        'scrollbarSlider.activeBackground': '#bfbfbf66',
        // Diff highlights from Aura; overview ruler kept strong for review readability.
        'diffEditor.insertedTextBackground': AURA.greenSoft,
        'diffEditor.removedTextBackground': AURA.redSoft,
        'diffEditor.insertedLineBackground': AURA.greenSoftLine,
        'diffEditor.removedLineBackground': AURA.redSoftLine,
        'diffEditor.border': AURA.borderStrong,
        'diffEditorOverview.insertedForeground': AURA.green,
        'diffEditorOverview.removedForeground': AURA.red,
    },
};

function stripHash(hex: string): string {
    return hex.startsWith('#') ? hex.slice(1) : hex;
}
