export const styles = {
    root: 'fixed inset-0 z-20 flex flex-col bg-zinc-950 text-zinc-100',
    shell: 'flex min-h-0 flex-1 flex-col bg-zinc-950',
    form: 'flex min-h-0 flex-1 flex-col',
    body: 'flex min-h-0 flex-1 flex-col gap-4 overflow-auto px-4 md:mx-auto md:w-full md:max-w-2xl',
    sectionHeader: 'mt-6',
    sectionTitle: 'text-2xl font-semibold tracking-tight text-zinc-100',
    sectionDescription: 'mt-1.5 text-sm text-zinc-500',
    loading: 'mt-8 text-sm text-zinc-500',
    fields: 'flex flex-col gap-4',
    label: 'block text-sm text-zinc-400',
    input: 'mt-1 w-full rounded-md border border-zinc-700 bg-zinc-900 px-3 py-2.5 text-base text-zinc-100 outline-none focus:border-aura-green',
    select: 'mt-1 w-full appearance-none rounded-md border border-zinc-700 bg-zinc-900 px-3 py-2.5 text-base text-zinc-100 outline-none focus:border-aura-green',
    footer: 'px-4 pt-4 pb-[max(1.5rem,env(safe-area-inset-bottom))] md:mx-auto md:w-full md:max-w-2xl',
};
